name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@main
        with:
          api_key: ${{ secrets.SEDSTART_API }}
          project_id: 473
          test_id: 2202
          profile_id: 968
          browser: chrome
          headless: false
          environment: QA
